-- liquibase formatted sql
-- changeset create_session_nonce_table:5
CREATE TABLE session_nonce (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nonce bytea NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_session_nonce_id PRIMARY KEY (id)
);

