# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build cdoc2-shares-server with CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  fork_setup:
    runs-on: ubuntu-latest

    outputs:
      base_repo: ${{ steps.base_repo.outputs.name }}
      is_fork: ${{ steps.is_fork.outputs.is_fork }}

    steps:
      # if pull_request and fork then finds base repo
      - id: base_repo
        run: |
          if [ "${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true }}" = "true" ]; then
            echo "name=${{github.event.pull_request.base.repo.full_name}}" >> "$GITHUB_OUTPUT"
          else
            echo "name=${{ github.event.repo.name }}" >> "$GITHUB_OUTPUT"
          fi
      - id: is_fork
        run: |
          if [ "${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true }}" = "true" ]; then
            echo "is_fork=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_fork=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    runs-on: ubuntu-latest
    needs: fork_setup

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4

        with:
          java-version: '17'
          distribution: 'temurin'
          overwrite-settings: true #generate settings.xml
          cache: maven

      - name: Build with Maven
        # temporary dislable tests as SID version of cdoc2-client is not available from GH
        run: |
          echo "Debug env vars: is_fork=$IS_FORK base_repo=$BASE_REPO MAVEN_REPO=$MAVEN_REPO"
          mvn help:active-profiles
          echo "Using Maven repo=$(mvn help:evaluate -Dexpression=github_ci.maven_repo -q -DforceStdout)"
          mvn -B verify -Dmaven.test.skip=true
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
          IS_FORK: ${{needs.fork_setup.outputs.is_fork}}
          BASE_REPO: ${{needs.fork_setup.outputs.base_repo}}
          MAVEN_REPO: ${{vars.MAVEN_REPO}} # set as repository variable: open-eid/cdoc2-shares-server


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
